typedef enum MEM_SWAP_MESSAGE
{
    OK = 1,
    CLOSE_CONNECTION,
  //MEM a SWAMP
    ADD_PAGE,
    ADD_PAGES,
    READ_PAGE,
    DELETE_PAGE,
    RELEASE_PROCESS,
    GET_PAGE_SIZE,
    GLOBAL_ASIGN,
    FIXED_ASIGN,
    IS_SPACE_SUFFICIENT,
  //SWAMP a MEM
    SUFFICIENT_SPACE,
    PAGE_ADDED,
    PAGES_ADDED,
    PAGE_READ,
    PAGE_DELETED,
    RETURN_PAGE,
    PROCESS_RELEASED,
    ERROR_PROCESS_NOT_FOUND,
    ERROR_PAGE_NOT_FOUND,
    ERROR_NO_SPACE_IN_SWAMP,
    ERROR_NO_SPACE_IN_PROCESS_FILE,
    ERROR_COULD_NOT_USE_FILE,
    ERROR_COULD_NOT_OPEN_FILE,
    ERROR_INCORRECT_PAGE_SIZE
} MEM_SWAP_MESSAGE;
